CREATE DATABASE FMP;

USE FMP;

CREATE TABLE PARKINGLOTS (
		PLOT_ID 			VARCHAR(20) PRIMARY KEY,
        PLOT_NAME 			VARCHAR(50),
        PLOT_PUBLIC 		BOOLEAN,
        PLOT_TYPE 			VARCHAR(10),
        PLOT_ROAD_ADD 		VARCHAR(200),
        PLOT_OLD_ADD 		VARCHAR(200),
        PLOT_SPACE_NUMS 	INT,
        PLOT_REGION_TYPE 	INT,
        PLOT_SYSTEM_TYPE	VARCHAR(10),
        PLOT_OPDAY_TYPE		VARCHAR(20),
        PLOT_REG_STARTTIME	TIME,
        PLOT_REG_ENDTIME	TIME,
		PLOT_SAT_STARTTIME	TIME,
        PLOT_SAT_ENDTIME	TIME,
        PLOT_HOL_STARTTIME	TIME,
        PLOT_HOL_ENDTIME	TIME,
        PLOT_FEE			VARCHAR(10),
        PLOT_DEF_TIME		DECIMAL,
        PLOT_DEF_FEE		DECIMAL,
        PLOT_UNI_TIME		DECIMAL,
        PLOT_UNI_FEE		VARCHAR(10),
        PLOT_TIC_TIME		DECIMAL,
        PLOT_TIC_FEE		DECIMAL,
        PLOT_MON_FEE		DECIMAL,
        PLOT_PAY_METHOD		VARCHAR(20),
        PLOT_REMARKS		VARCHAR(100),
        PLOT_MAN_ORG		VARCHAR(100),
        PLOT_PHONE			VARCHAR(20),
        PLOT_LAT			DECIMAL,
        PLOT_LONG			DECIMAL
);