# Generated by Django 3.2.7 on 2022-08-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parkinglot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=50, verbose_name='p_id')),
                ('p_name', models.CharField(max_length=200, verbose_name='p_name')),
                ('p_long', models.FloatField(verbose_name='p_long')),
                ('p_lat', models.FloatField(verbose_name='p_lat')),
                ('p_num', models.IntegerField(verbose_name='p_num')),
            ],
        ),
    ]
